/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NMA_H_RPCGEN
#define _NMA_H_RPCGEN

#include <rpc/rpc.h>


#define NMA_PROG 1
#define NMA_VERS 1
#define get_sys_info 1
extern  char ** get_sys_info_1();
extern int nma_prog_1_freeresult ();

#endif /* !_NMA_H_RPCGEN */
