package AuctionApp;

/**
* AuctionApp/AuctionFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, April 6, 2014 2:45:20 AM CDT
*/

public final class AuctionFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public AuctionApp.AuctionFactory value = null;

  public AuctionFactoryHolder ()
  {
  }

  public AuctionFactoryHolder (AuctionApp.AuctionFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuctionApp.AuctionFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuctionApp.AuctionFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuctionApp.AuctionFactoryHelper.type ();
  }

}
