package AuctionApp;


/**
* AuctionApp/AuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, April 6, 2014 2:45:20 AM CDT
*/

public interface AuctionOperations 
{

  // Raises MAX_AUCTIONS_REACHED exception if an auction is already active
  void offerItem (String userId, String itemDesc, int price) throws AuctionApp.AuctionFailure;

  // Raises NO_ACTIVE_AUCTION exception if no auction is active
  String viewHighBidder (String userId) throws AuctionApp.AuctionFailure;

  // Raises NO_ACTIVE_AUCTION exception if no auction is active
  void sellItem (String userId) throws AuctionApp.AuctionFailure;

  // If called by a bidder, returns auction state, item description, and item price
  void viewAuctionStatus (String userId, org.omg.CORBA.BooleanHolder isActive, org.omg.CORBA.StringHolder itemDesc, org.omg.CORBA.IntHolder price, org.omg.CORBA.StringHolder highBidder);

  // Raises ACTION_NOT_PERMITTED exception when called by the seller
  void bid (String userId, int price) throws AuctionApp.AuctionFailure;

  // Raises ACTION_NOT_PERMITTED exception when not called by the Auction Manager
  String viewSeller (String userId) throws AuctionApp.AuctionFailure;
} // interface AuctionOperations
