package AuctionApp;

/**
* AuctionApp/AuctionFailureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, April 6, 2014 2:45:20 AM CDT
*/

public final class AuctionFailureHolder implements org.omg.CORBA.portable.Streamable
{
  public AuctionApp.AuctionFailure value = null;

  public AuctionFailureHolder ()
  {
  }

  public AuctionFailureHolder (AuctionApp.AuctionFailure initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuctionApp.AuctionFailureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuctionApp.AuctionFailureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuctionApp.AuctionFailureHelper.type ();
  }

}
