package AuctionApp;


/**
* AuctionApp/AuctionFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, April 6, 2014 2:45:20 AM CDT
*/

public interface AuctionFactoryOperations 
{

  // Raises INVALID_USER exception if the userId is in the database, but the password doesn't match
  void authenticate (String userId, String password) throws AuctionApp.AuctionFailure;

  // Raises GENERIC_ERROR if an error occurs when contacting the auction servers
  void getActiveAuctions (String userId, AuctionApp.AuctionFactoryPackage.AuctionsHolder sellerAuctions, org.omg.CORBA.IntHolder numSellerAuctions, AuctionApp.AuctionFactoryPackage.AuctionsHolder bidderAuctions, org.omg.CORBA.IntHolder numBidderAuctions) throws AuctionApp.AuctionFailure;

  // Raises GENERIC_ERROR if an error occurs when contacting the auction servers
  String getInactiveAuction () throws AuctionApp.AuctionFailure;
} // interface AuctionFactoryOperations
