package AuctionApp;


/**
* AuctionApp/ErrorTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, April 6, 2014 2:45:20 AM CDT
*/

abstract public class ErrorTypeHelper
{
  private static String  _id = "IDL:AuctionApp/ErrorType:1.0";

  public static void insert (org.omg.CORBA.Any a, AuctionApp.ErrorType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AuctionApp.ErrorType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (AuctionApp.ErrorTypeHelper.id (), "ErrorType", new String[] { "MAX_AUCTIONS_REACHED", "NO_ACTIVE_AUCTION", "ACTION_NOT_PERMITTED", "INVALID_USER", "GENERIC_ERROR"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AuctionApp.ErrorType read (org.omg.CORBA.portable.InputStream istream)
  {
    return AuctionApp.ErrorType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AuctionApp.ErrorType value)
  {
    ostream.write_long (value.value ());
  }

}
