package AuctionApp;


/**
* AuctionApp/ErrorType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, April 6, 2014 2:45:20 AM CDT
*/

public class ErrorType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 5;
  private static AuctionApp.ErrorType[] __array = new AuctionApp.ErrorType [__size];

  public static final int _MAX_AUCTIONS_REACHED = 0;
  public static final AuctionApp.ErrorType MAX_AUCTIONS_REACHED = new AuctionApp.ErrorType(_MAX_AUCTIONS_REACHED);
  public static final int _NO_ACTIVE_AUCTION = 1;
  public static final AuctionApp.ErrorType NO_ACTIVE_AUCTION = new AuctionApp.ErrorType(_NO_ACTIVE_AUCTION);
  public static final int _ACTION_NOT_PERMITTED = 2;
  public static final AuctionApp.ErrorType ACTION_NOT_PERMITTED = new AuctionApp.ErrorType(_ACTION_NOT_PERMITTED);
  public static final int _INVALID_USER = 3;
  public static final AuctionApp.ErrorType INVALID_USER = new AuctionApp.ErrorType(_INVALID_USER);
  public static final int _GENERIC_ERROR = 4;
  public static final AuctionApp.ErrorType GENERIC_ERROR = new AuctionApp.ErrorType(_GENERIC_ERROR);

  public int value ()
  {
    return __value;
  }

  public static AuctionApp.ErrorType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ErrorType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ErrorType
