package AuctionApp;

/**
* AuctionApp/ErrorTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, April 6, 2014 2:45:20 AM CDT
*/

public final class ErrorTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public AuctionApp.ErrorType value = null;

  public ErrorTypeHolder ()
  {
  }

  public ErrorTypeHolder (AuctionApp.ErrorType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuctionApp.ErrorTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuctionApp.ErrorTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuctionApp.ErrorTypeHelper.type ();
  }

}
