package AuctionApp.AuctionFactoryPackage;


/**
* AuctionApp/AuctionFactoryPackage/AuctionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from auction.idl
* Sunday, April 6, 2014 2:45:20 AM CDT
*/

public final class AuctionsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public AuctionsHolder ()
  {
  }

  public AuctionsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuctionApp.AuctionFactoryPackage.AuctionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuctionApp.AuctionFactoryPackage.AuctionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuctionApp.AuctionFactoryPackage.AuctionsHelper.type ();
  }

}
